#Analyzing Indonesia's logs using Emre's script.

CDRs were converted from SQLITe to the log file format (csv) - similar to Philipines data.

```{r}
#Loading libraries
suppressMessages(require(data.table))
suppressMessages(require(ggplot2))
source('./functions.R')
suppressMessages(require(XML))
require('knitr')
```

Once libraries are loaded, take individual files and merge it in a datatable
```{r}
files <- list.files(path = 'imsis_id_endaga/', pattern='*.log')
files <- paste('imsis_id_endaga/', files, sep = '')
imsiraw <- rbindlist(lapply(files, function(x) {fread(x, colClasses = c('character',                               'character', 'integer', 'integer', 'integer'))}))
setnames(imsiraw,c('imsi','imei','accessed','created','is_auth'))
head(imsiraw[,.N,.(imsi,imei)][,.N,imei])
```

Some data processing
```{r}
# process the date and time
head(imsiraw[,created_dt:=as.POSIXct(created, origin="1970-01-01", tz = "GMT")])
head(imsiraw[,created_ds:=as.Date(created_dt)])
head(imsiraw[,created_hour:=hour(created_dt)])

head(imsiraw[,accessed_dt:=as.POSIXct(accessed, origin="1970-01-01", tz = "GMT")])
head(imsiraw[,accessed_ds:=as.Date(accessed_dt)])
head(imsiraw[,accessed_hour:=hour(accessed_dt)])

# figure out the weekday
head(imsiraw[,dayofweek:=weekdays(accessed_ds, abbreviate = TRUE)])
# cast day of the week as factor and order them
head(imsiraw[,dayofweek:=factor(dayofweek, ordered = TRUE, 
                           levels = c('Sun', 'Sat', 'Fri', 'Thu',  'Wed', 'Tue', 'Mon'))])

# Calculate the check digit
head(imsiraw[,checkdigit:=checkDigitCalc(imei)])
# create the corrected imei
head(imsiraw[,imeicorrected:=paste(substr(imei,1,14),checkdigit,sep = '')])
# Add weekend/weekday identifier
head(imsiraw[,weekend:=FALSE])
head(imsiraw[dayofweek %in% c('Sun','Sat'),weekend:=TRUE])
# make all is_auth > 0 to be 1 since they are all authorized
head(imsiraw[is_auth>0,is_auth:=1])
# figure out first time an imei is observed
head(imsiraw[,first_encounter_with_imei:=min(accessed_ds),imeicorrected])
# figure out first time an imsi is observed
head(imsiraw[,first_encounter_with_imsi:=min(accessed_ds),imsi])
```

```{r}
# Check what % of IMEI before launch did not become a user
imsi_prelaunch<-imsiraw[accessed_ds<'2016-01-30']
imsi_postlaunch<-imsiraw[accessed_ds>='2016-01-30']
# determine which IMEIs were around prelaunch
head(imsi_postlaunch[,prelaunch:=0])
head(imsi_postlaunch[imeicorrected%in%imsi_prelaunch[is_auth==0,.N,imeicorrected][,imeicorrected],prelaunch:=1])
```

```{r}
head(imsiraw[,TAC:=substr(imeicorrected,1,8)])
# location to the tac DB
tacdb<-fread('MSRPLUS20161101.txt',colClasses = "character")
imsi_mapped <- merge(imsiraw, tacdb, by="TAC", all.x=TRUE)

imsi_mapped<-imsi_mapped[!is.na(`Marketing Name`)]

head(imsi_mapped[,.N,.(imeicorrected,`Device Type`)][,.N,.(`Device Type`)])
```

```{r}
#get mccmnc list
mccmnc<-readHTMLTable('http://www.imei.info/operator-codes/')
mccmnc<-data.table(mccmnc[[1]])
setnames(mccmnc,c('Code','Operator','Country'))
mccmnc <- mccmnc[Code!='Code']
head(mccmnc[,Code:=gsub(' ','',Code)])


head(merge(imsiraw[,.N,.(imsi,Code=substr(imsi,1,5))][,.N,Code][order(-N)],mccmnc,by='Code')[order(-N)])
head(imsiraw[,.N,.(imeicorrected,is_auth)][,.N,is_auth])
```

```{r}
head(imsi_mapped[,.N,.(imeicorrected,`Device Type`)][,.N,.(`Device Type`)][order(-N)])
head(imsi_mapped[,.N,.(imeicorrected,`Operating System`)][,.N,.(`Operating System`)][order(-N)])
head(imsi_mapped[`Device Type`=='Smartphone',.N,.(imeicorrected,Band)][,.N,.(Band)][order(-N)])
head(imsi_mapped[,lte:='N'])
head(imsi_mapped[grepl('LTE',Band),lte:='Y'])
head(imsi_mapped[lte=='N',.N,Band])
head(imsi_mapped[,threeG:='N'])
head(imsi_mapped[grepl('CDMA',Band),threeG:='Y'])
head(imsi_mapped[grepl('UMTS',Band),threeG:='Y'])
head(imsi_mapped[grepl('HSDPA',Band),threeG:='Y'])
head(imsi_mapped[grepl('HSUPA',Band),threeG:='Y'])
head(imsi_mapped[grepl('Bluetooth',Band),Bluetooth:='Y'])
```

```{r}
# newcoming lte capable handsets overtime
lte_ts<-imsi_mapped[,.N,.(year(first_encounter_with_imei),month(first_encounter_with_imei),imeicorrected,lte)][,.N,.(year,month,lte)][order(lte,year,month)]
lte_ts<-dcast.data.table(lte_ts,year+month~lte,fun=sum)
head(lte_ts[,T:=Y+N])
lte_ts[,Y_perc:=Y/T]
```

```{r}
# only authorized users
auth_lte_ts<-imsi_mapped[is_auth==1,.N,.(year(first_encounter_with_imei),month(first_encounter_with_imei),imeicorrected,lte)][,.N,.(year,month,lte)][order(lte,year,month)]
auth_lte_ts<-dcast.data.table(auth_lte_ts,year+month~lte,fun=sum)
head(auth_lte_ts[,T:=Y+N])
auth_lte_ts[,Y_perc:=Y/T]
```

```{r}
# all phones
auth_allphones_lte_ts<-imsi_mapped[is_auth==1,.N,.(year(accessed_ds),month(accessed_ds),imeicorrected,lte)][,.N,.(year,month,lte)][order(lte,year,month)]
auth_allphones_lte_ts<-dcast.data.table(auth_allphones_lte_ts,year+month~lte,fun=sum)
head(auth_allphones_lte_ts[,T:=Y+N])
auth_allphones_lte_ts[,Y_perc:=Y/T]
```

```{r}
# all phones including passer byers
allphones_lte_ts<-imsi_mapped[,.N,.(year(accessed_ds),month(accessed_ds),imeicorrected,lte)][,.N,.(year,month,lte)][order(lte,year,month)]
allphones_lte_ts<-dcast.data.table(allphones_lte_ts,year+month~lte,fun=sum)
head(allphones_lte_ts[,T:=Y+N])
allphones_lte_ts[,Y_perc:=Y/T]
```

```{r}
# newcoming three G capable handsets overtime
threeG_ts<-imsi_mapped[,.N,.(year(first_encounter_with_imei),month(first_encounter_with_imei),imeicorrected,threeG)][,.N,.(year,month,threeG)][order(threeG,year,month)]
threeG_ts<-dcast.data.table(threeG_ts,year+month~threeG,fun=sum)
head(threeG_ts[,T:=Y+N])
threeG_ts[,Y_perc:=Y/T]
```

```{r}
# some misc cuts
head(imsi_mapped[,.N,.(TAC,`Manufacturer (or) Applicant`)][,.N,`Manufacturer (or) Applicant`][order(-N)])
head(imsi_mapped[,.N,.(TAC,`Marketing Name`)][,.N,`Marketing Name`][order(-N)])
head(imsi_mapped[,.N,.(TAC,`Brand Name`)][,.N,`Brand Name`][order(-N)])
head(imsi_mapped[,.N,.(TAC,`Model Name`)][,.N,`Model Name`][order(-N)])
head(imsi_mapped[,.N,.(TAC,`Device Type`)][,.N,`Device Type`][order(-N)])
head(imsi_mapped[,.N,.(TAC,`Operating System`)][,.N,`Operating System`][order(-N)])
```